# Generated by Django 4.0.4 on 2022-06-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('pub_date', models.DateField()),
                ('ISBN_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_names', models.TextField(blank=True, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=255, unique=True)),
                ('date_of_birth', models.DateField()),
                ('department', models.TextField(blank=True, null=True)),
                ('employee_number', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=255)),
                ('is_staff', models.BooleanField(blank=True)),
                ('is_admin', models.BooleanField(blank=True)),
                ('is_student', models.BooleanField(blank=True)),
            ],
        ),
    ]
